### ISSUE TITLE
Update package.json to ensure extension can run in different extension host setups

### ISSUE THREAD

**Issue by bamurtaugh** [sgryjp/japanese-word-handler#11]
Hi! I'm from the VS Code team, and we'd like to ensure Japanese Word Handler can run in the different extension host setups VS Code currently supports. I've found that the current definition of `extensionKind` for your extension is too restrictive.

The extension has the `extensionKind` set to `["ui"]`: https://github.com/sgryjp/japanese-word-handler/blob/master/package.json#L17. This defines that the extension can only run in the VS Code desktop extension host. 

However, this extension can also run on the workspace extension host (which is used for remote scenarios) since it doesn't have any dependencies on the desktop extension host. It'd also be great to enable it for Codespaces web.

Thus, to ensure your extension can run properly across setups, we'd recommend to change the extensionKind to `"extensionKind": ["ui", "workspace"]`. More information about `extensionKind` can be found [here](https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location).

Please let me know if you have questions - I'm happy to help clarify anything. Thank you!

**Comment by bamurtaugh** [comment]
Hey @sgryjp - just wanted to check in to see if there is any additional info I might be able to provide to help with this, or if it would be more helpful for me to open a PR with the change. Thank you!

**Comment by sgryjp** [comment]
Hi @bamurtaugh. I'm sorry that I couldn't make any action for this issue. Actually, I have been extremely busy these days to spare time for my personal projects. As soon as I can make some free time, I'll take an action for this issue with top priority. Thank you.

**Comment by bamurtaugh** [comment]
Thanks for your response @sgryjp! Let me know if you have any questions or I can provide any support.

**Comment by sgryjp** [comment]
Although I cannot test the fix on Codespaces since I don't have access to the service yet, the new setting value `["ui", "workspace"]` must be fine as it is the backward-compatible value:

> - `"extensionKind": ["ui", "workspace"]`
>   ...
>   The old "ui" value (as a string) maps to this type for backwards compatibility, but is considered deprecated.
>
> &mdash;https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location

Thank you for supporting me, @bamurtaugh !
