### ISSUE TITLE
Web Extensionに変更する

### ISSUE THREAD

**Issue by sgryjp** [sgryjp/japanese-word-handler#15]
japanese-word-handler cannot be used on web services such as GitHub Cocespaces and vscode.dev because it is not a web extension. To make it possible, it should be changed into a web extension.

---

Codespaces で使えない理由の一つになっているので、通常の Extension から Web Extension にマイグレーションする。

---

Reference: https://code.visualstudio.com/api/extension-guides/web-extensions#update-existing-extensions-to-web-extensions

**Comment by sgryjp** [comment]
Confirmed it's working on `vscode.dev` and `github.dev`.

**Comment by Altdarkzodiac** [comment]
Let's get this up
