### ISSUE TITLE
v1.4.0 does not work on local VS Code 

### ISSUE THREAD

**Issue by tekezo** [sgryjp/japanese-word-handler#16]
`command 'japaneseWordHandler.*' not found` error will be raised for all japaneseWordHandler commands on local VS Code with Japanese Word Handler v1.4.0.

v1.3.0 works well on same environment.

I guess the migrated web extension is not loaded on local VS Code.

<img width="542" alt="Screen Shot 2021-11-06 at 7 47 34" src="https://user-images.githubusercontent.com/659178/140586646-34323128-c5ce-4554-bbe2-0b2da53d0b7a.png">

**Comment by sgryjp** [comment]
Thank you for letting me know this! I examine this ASAP.

**Comment by sgryjp** [comment]
Okay, confirmed that v1.4.1 works on both desktop and web environment. Thank you @tekezo !

**Comment by tekezo** [comment]
v1.4.1 works fine! Thank you!
