### ISSUE TITLE
`Ctrl + Backspace or Delete` fails in preference settings input box

### ISSUE THREAD

**Issue by lingsamuel** [sgryjp/japanese-word-handler#5]
`Ctrl + Backspace` and `Ctrl + Delete` produce similar error: `japaneseWordHandler.deleteWordStartLeft` and `japaneseWordHandler.deleteWordEndRight`.

In `File/Preferences/Settings` input box:
![image](https://user-images.githubusercontent.com/14567045/80200391-276cb800-8655-11ea-88ae-bb5c3029ae0c.png)

**Comment by lingsamuel** [comment]
Ext host log:
```
[2020-04-24 17:59:39.735] [exthost] [error] TypeError: Cannot read property 'document' of undefined
    at /home/lingsamuel/.vscode/extensions/sgryjp.japanese-word-handler-1.2.0/out/extension.js:11:52
...
```

The code:
```js
let editor = vscode.window.activeTextEditor;
// ...
.getConfiguration("editor", editor.document.uri)
// ...
```

Seems that this GUI (or a rendered page?) doesn't have variable `vscode.window.activeTextEditor`.

**Comment by lingsamuel** [comment]
Found solution in fork [CJK-word-handler](https://github.com/sgryjp/japanese-word-handler), [commit here](https://github.com/SharzyL/cjk-word-handler/commit/bcf1e775608e4caa9c5b4d61678ae01e7a5255aa#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L119)

```json
"when": "textInputFocus && !editorReadonly"
```

To:

```json
"when": "editorTextFocus && !editorReadonly"
```

**Comment by sgryjp** [comment]
Thank you for reporting!
I reproduced the issue, and also confirmed the solution you mentioned. I'll make some time to fix this so please wait some days.
