### ISSUE TITLE
ReadMeのKeybinding表記

### ISSUE THREAD

**Issue by shuGH** [sgryjp/japanese-word-handler#7]
便利に使わせて頂いております
細かい事で恐縮ですが、ReadMeの以下のキーバインドがRightになっていました
japaneseWordHandler.cursorWordStartLeft
japaneseWordHandler.cursorWordStartLeftSelect

**Comment by sgryjp** [comment]
お知らせありがとうございます。ご指摘の通り、間違っていました。。。追って、直しますね。

追伸：[Table Formatter](https://marketplace.visualstudio.com/items?itemName=shuworks.vscode-table-formatter)、長いこと便利に使わせていただいております。これが無いと Markdown で表を書こうという気になれません。素晴らしい拡張機能、ありがとうございます。

**Comment by sgryjp** [comment]
修正完了につきクローズします。

**Comment by shuGH** [comment]
ご対応ありがとうございます
こちらこそ、もうずっとメンテしてなくて恥ずかしいですが、TableFormatterもお役に立っているようで嬉しい限りです
